@startuml
title Identity & Access ↔ Clinical Context
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle

package "Shared Kernel" {

class "EmployeeId" <<ValueObject>> {
- value : UUID
}

class "DateTime" <<ValueObject>> {
- value : Date
}
}

package "Identity & Access Context" {
class "SessionId" <<ValueObject>> {
- value : UUID
}
entity "OpticalEmployee" <<AggregateRoot>> {
  - id : EmployeeId
  --
  name : String
  email : String
  phone : String
  password : String
  role : EmployeeRole
  department : String
  status : EmployeeStatus    ← activo/inactivo
  hireDate : DateTime
  permissions : String
  --
  + generateSession(): Session
  + changePassword(newPassword: String): void
  + validateCredentials(): Boolean
  + deactivate(): void       ← para estado inactivo
}

enum EmployeeStatus {
  ACTIVE
  INACTIVE
}
entity "Session" <<Entity>> {
- id : SessionId
--
token : String
expiresAt : DateTime
--
+ invalidate()
+ isActive(): Boolean
}
enum EmployeeRole {
ADMIN
SALES_ADVISOR
OPTOMETRIST
LAB_TECHNICIAN
}
OpticalEmployee *--> "0..*" Session
OpticalEmployee --> EmployeeRole
Session --> SessionId
Session --> DateTime
OpticalEmployee --> EmployeeId
OpticalEmployee --> EmployeeStatus

}

@enduml

